---
- name: Universal Server Patch Management
  hosts: all
  become: yes
  tasks:

    # ---------------------------------------------------------
    # DEBIAN / UBUNTU FAMILY
    # ---------------------------------------------------------
    - name: Update packages (Legacy Debian 10 & Ubuntu 20 - Shell Workaround)
      ansible.builtin.shell: apt-get update && apt-get dist-upgrade -y
      when: 
        - ansible_facts['os_family'] == "Debian"
        - (ansible_facts['distribution'] == 'Debian' and ansible_facts['distribution_major_version'] == '10') or (ansible_facts['distribution'] == 'Ubuntu' and ansible_facts['distribution_major_version'] == '20')

    - name: Update packages (Modern Debian 11+ & Ubuntu 22+)
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist
      when: 
        - ansible_facts['os_family'] == "Debian"
        - (ansible_facts['distribution'] == 'Debian' and ansible_facts['distribution_major_version'] | int >= 11) or (ansible_facts['distribution'] == 'Ubuntu' and ansible_facts['distribution_major_version'] | int >= 22)


    # ---------------------------------------------------------
    # REDHAT / CENTOS / ROCKY FAMILY
    # ---------------------------------------------------------
    - name: Update packages (Legacy CentOS 4 and CentOS 7 - Shell Workaround)
      ansible.builtin.shell: yum clean all && yum update -y
      when: 
        - ansible_facts['os_family'] == "RedHat"
        - ansible_facts['distribution_major_version'] | int <= 7

    - name: Update packages (Modern Rocky / CentOS 8+)
      ansible.builtin.dnf:
        name: '*'
        state: latest
        update_cache: yes
      when: 
        - ansible_facts['os_family'] == "RedHat"
        - ansible_facts['distribution_major_version'] | int >= 8
